### ISSUE TITLE
package.json at the top level

### ISSUE THREAD

**Issue by markkovari** [gfa-cc-after/Avengers_PET_Clinic#23]
https://github.com/gfa-cc-after/Avengers_PET_Clinic/blob/ef67236d70da9c1b001e9d4da23754e82c2030f8/package-lock.json#L1-L13

We currently do not use anything on the top level, which requires node (or package.json) to be present. Do you see any benefit or should we remove it?

**Comment by ReneVajda1** [comment]
![image](https://github.com/user-attachments/assets/09f89aef-e7f2-49be-91a8-07c4dc07a9ef)

**Comment by ReneVajda1** [comment]
all solved
