### ISSUE TITLE
Config vs Configuration

### ISSUE THREAD

**Issue by markkovari** [gfa-cc-after/Avengers_PET_Clinic#24]
Last time @ReneVajda1 called out, that we are duplicating packages. Now I was faster 😅 
https://github.com/gfa-cc-after/Avengers_PET_Clinic/tree/main/Backend-API/src/main/java/com/avangers/backendapi
We probably should've only `config` or `configuration` and move the classes in one package.

**Comment by ReneVajda1** [comment]
Lol I just told about it to juraj but went to cook before coding ![20240719_191314.jpg](https://github.com/user-attachments/assets/0b14fc05-8b97-4a45-bdac-98c483b2f310)

**Comment by ReneVajda1** [comment]
all resolved
