### ISSUE TITLE
ResponeEntity in services

### ISSUE THREAD

**Issue by markkovari** [gfa-cc-after/Avengers_PET_Clinic#25]
https://github.com/gfa-cc-after/Avengers_PET_Clinic/blob/ef67236d70da9c1b001e9d4da23754e82c2030f8/Backend-API/src/main/java/com/avangers/backendapi/services/UserServiceImpl.java#L19

This is not the most essential, but if we are using this return type here we commit to use only http. Which we shouldn't since there are many alternatives like (command line, WebSocket, GraphQL, gRPC, etc), which might just wanted to get objects not not a struct which is related to a protocol.

We rather should use classes (and objects) which are not related to http here.

**Comment by Metemi** [comment]
Oh OK so I did not understand that correctly first time

**Comment by ReneVajda1** [comment]
as we went on with jwt generation branch im gonna create separate branch with separate pr on this issue for safety
