### ISSUE TITLE
We should use the interfaces where appropriate

### ISSUE THREAD

**Issue by markkovari** [gfa-cc-after/Avengers_PET_Clinic#26]
https://github.com/gfa-cc-after/Avengers_PET_Clinic/blob/ef67236d70da9c1b001e9d4da23754e82c2030f8/Backend-API/src/main/java/com/avangers/backendapi/controllers/UserController.java#L19

We created (if I recall correctly) an interface, but did not use it.

This is the interface right now:
![image](https://github.com/user-attachments/assets/eccfd84e-1a06-46f3-9784-7bf66a017100)

Please don't let the interface to be sad. Thanks

**Comment by ReneVajda1** [comment]
all resolved
